### PR TITLE
Return error for queries with specific block height

### LINKED ISSUE #1438: RunQuery denial of service
**Describe the bug**

A specially crafted message can cause denial of service.

**Steps To Reproduce**

Send a query with BlockHeight parameter set to something other than 0.

**Expected behavior**

No denial of service should occur.

**Additional context**

https://github.com/orbs-network/orbs-network-go/blob/09453950f16a62fcc1ddf16543496d8a976ab8fa/services/virtualmachine/service.go#L59

### PR DESCRIPTION
**Pull request by netoneko**
Fixes #1438

### CODE REVIEW

File: services/virtualmachine/service.go [hunk 1]
```diff
@@ -57,7 +57,13 @@ func (s *service) ProcessQuery(ctx context.Context, input *services.ProcessQuery
 	logger := s.logger.WithTags(trace.LogFieldFrom(ctx))
 
 	if input.BlockHeight != 0 {
-		panic("Run local method with specific block height is not yet supported")
+		err := errors.New("Run local method with specific block height is not yet supported")
+		return &services.ProcessQueryOutput{
+			CallResult:              protocol.EXECUTION_RESULT_ERROR_INPUT,
```
Comment (noambergIL) [inline services/virtualmachine/service.go]: my thought is to use the protocol.ArgumentsArrayEmpty().Raw() instead of just empty byte array and also to return the last committed block height and time even if there is nothing that can be done with it. 
please also change the other error in this func to have the argumens empty thing. thanks

Comment (netoneko) [reply services/virtualmachine/service.go]: Done

File: services/virtualmachine/service.go [hunk 2]
```diff
@@ -56,15 +56,21 @@ func NewVirtualMachine(
...
 			CallResult:              protocol.EXECUTION_RESULT_ERROR_UNEXPECTED,
-			OutputArgumentArray:     []byte{},
+			OutputArgumentArray:     protocol.ArgumentsArrayEmpty().Raw(),
+			ReferenceBlockHeight:    committedBlockHeight,
+			ReferenceBlockTimestamp: committedBlockTimestamp,
+		}, err
+	}
+
+	if input.BlockHeight != 0 {
+		err := errors.New("Run local method with specific block height is not yet supported")
```
Comment (golangcibot) [inline services/virtualmachine/service.go]: shadow: declaration of "err" shadows declaration at line 59 (from `govet`)

File: services/virtualmachine/service.go [hunk 3]
```diff
@@ -56,15 +56,21 @@ func NewVirtualMachine(
...
 		return &services.ProcessQueryOutput{
 			CallResult:              protocol.EXECUTION_RESULT_ERROR_UNEXPECTED,
-			OutputArgumentArray:     []byte{},
+			OutputArgumentArray:     protocol.ArgumentsArrayEmpty().Raw(),
+			ReferenceBlockHeight:    committedBlockHeight,
+			ReferenceBlockTimestamp: committedBlockTimestamp,
+		}, err
+	}
+
+	if input.BlockHeight != 0 {
```
Comment (noambergIL) [inline services/virtualmachine/service.go]: you have changed order of execution ...
