### PR TITLE
extract ticker from PeriodicalTrigger, rewrite tests (simplified)

### LINKED ISSUE #1416: TestPeriodicalTriggerStopWorksWhenContextIsCancelled fails on goroutine not supervised
```
=== RUN   TestPeriodicalTriggerStopWorksWhenContextIsCancelled
--- FAIL: TestPeriodicalTriggerStopWorksWhenContextIsCancelled (0.00s)
    test_output.go:97: e 07:42:17.891567 recovered panic error=Forever governed goroutine a periodical trigger terminated without being supervised panic=true stack-trace=goroutine 52 [running]:
        runtime/debug.Stack(0x844e40, 0xc000196ea0, 0xc00016e5e0)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
        github.com/orbs-network/orbs-network-go/instrumentation/logfields.(*govnrErrorer).Error(0xc000176710, 0x8e1e80, 0xc00016e5e0)
        	/home/circleci/project/instrumentation/logfields/govnr_error_handler.go:18 +0xef
        github.com/orbs-network/govnr.(*ForeverHandle).terminated(0xc000182800)
        	/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/forever.go:63 +0x11a
        github.com/orbs-network/govnr.Forever.func1(0xc000182800, 0x8e1d60, 0xc000176710, 0xc00016e5a0, 0x8e8f60, 0xc0001827c0)
        	/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/forever.go:79 +0x86
        created by github.com/orbs-network/govnr.Forever
        	/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/forever.go:73 +0xfc
         function=logfields.(*govnrErrorer).Error source=/home/circleci/project/instrumentation/logfields/govnr_error_handler.go:18 
    test_output.go:98: Test failed due to unexpected errors being logged. If the error above is expected, please add it to the list of allowed errors by invoking TestOutput.AllowErrorsMatching
    logging.go:40: Test failed; encountered unexpected errors
FAIL
FAIL	github.com/orbs-network/orbs-network-go/synchronization	0.093s
```

https://circleci.com/gh/orbs-network/orbs-network-go/21203?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### PR DESCRIPTION
**Pull request by amir-arad**
fixes #1416

### CODE REVIEW

File: synchronization/trigger_test.go [hunk 1]
```diff
@@ -26,120 +26,133 @@ func newNopLogger() *nopLogger {
...
+func (c *TestFlag) Toggle() {
+	atomic.StoreUint32(&(c.count), 1)
+}
+func (c *TestFlag) EventuallyToggled(message string) {
+	require.Eventually(c.t, func() bool { return atomic.CompareAndSwapUint32(&(c.count), 1, 0) }, time.Second, time.Millisecond, message)
+}
 
-	p.Stop()
+func (c *TestFlag) NotEventuallyToggled(message string) {
+	time.Sleep(time.Millisecond * 500)
```
Comment (electricmonk) [inline synchronization/trigger_test.go]: rename `NeverToggled`

File: synchronization/trigger_test.go [hunk 2]
```diff
@@ -26,120 +26,133 @@ func newNopLogger() *nopLogger {
...
 }
 
-func TestPeriodicalTrigger_StopAfterTrigger(t *testing.T) {
+func TestPeriodicalTriggerTriggersOnTicks(t *testing.T) {
 	with.Concurrency(t, func(ctx context.Context, harness *with.ConcurrencyHarness) {
-		x := 0
-		p := synchronization.NewPeriodicalTrigger(context.Background(), "a periodical trigger", time.Millisecond, harness.Logger, func() { x++ }, nil)
+		ticker := synchronization.NewHookTicker()
+		ch := make(chan time.Time)
+		ticker.C_ = func() <-chan time.Time { return ch }
```
Comment (electricmonk) [inline synchronization/trigger_test.go]: why not make the `HookTrigger` the owner (creator) of the channel?

File: synchronization/trigger_test.go [hunk 3]
```diff
@@ -26,120 +26,133 @@ func newNopLogger() *nopLogger {
...
-		ctx, cancel := context.WithCancel(parent)
-		cancel() // send a cancelled context to reduce chances of trigger being called even once
-		x := 0
-		p := synchronization.NewPeriodicalTrigger(ctx, "a periodical trigger", time.Millisecond*2, harness.Logger, func() { x++ }, nil)
+func TestPeriodicalTriggerStopsTickerOnCallToStop(t *testing.T) {
+	with.Concurrency(t, func(ctx context.Context, harness *with.ConcurrencyHarness) {
+		ticker := synchronization.NewHookTicker()
+		wasStopped := NewTestFlag(t)
+		ticker.Stop_ = func() { wasStopped.Toggle() }
+		p := synchronization.NewPeriodicalTrigger(context.Background(), "a periodical trigger", ticker, harness.Logger, func() {}, nil)
```
Comment (electricmonk) [inline synchronization/trigger_test.go]: why not use `ctx`?

File: synchronization/trigger_test.go [hunk 4]
```diff
@@ -26,120 +26,133 @@ func newNopLogger() *nopLogger {
...
-	with.Concurrency(t, func(parent context.Context, harness *with.ConcurrencyHarness) {
-		ctx, cancel := context.WithCancel(parent)
-		cancel() // send a cancelled context to reduce chances of trigger being called even once
-		x := 0
-		p := synchronization.NewPeriodicalTrigger(ctx, "a periodical trigger", time.Millisecond*2, harness.Logger, func() { x++ }, nil)
+func TestPeriodicalTriggerStopsTickerOnCallToStop(t *testing.T) {
+	with.Concurrency(t, func(ctx context.Context, harness *with.ConcurrencyHarness) {
+		ticker := synchronization.NewHookTicker()
+		wasStopped := NewTestFlag(t)
+		ticker.Stop_ = func() { wasStopped.Toggle() }
```
Comment (electricmonk) [inline synchronization/trigger_test.go]: maybe you can do `ticker.Stop_ = wasStopped.Toggle`

File: synchronization/trigger_test.go [hunk 5]
```diff
@@ -26,120 +26,133 @@ func newNopLogger() *nopLogger {
...
-		p := synchronization.NewPeriodicalTrigger(context.Background(), "a periodical trigger", time.Millisecond, logger, func() {
-			atomic.AddUint32(&handlerInvocationCount, 1)
-			panic("we should not see this other than the logs")
-		}, nil)
-
-		requireAtomicGreaterThan(t, &handlerInvocationCount, 1, "expected trigger to have ticked more than once even though it panics")
-
-		p.Stop()
+		ctx, cancel := context.WithCancel(parent)
+		ticker := synchronization.NewHookTicker()
```
Comment (electricmonk) [inline synchronization/trigger_test.go]: you could create another implementation local to the test, `NopTrigger`

File: synchronization/trigger_test.go [hunk 6]
```diff
@@ -26,120 +26,133 @@ func newNopLogger() *nopLogger {
...
 
-func TestPeriodicalTriggerStopOnContextCancelWithStopAction(t *testing.T) {
+func TestPeriodicalTriggerStopsTickerOnContextCancel(t *testing.T) {
 	with.Concurrency(t, func(parent context.Context, harness *with.ConcurrencyHarness) {
 		ctx, cancel := context.WithCancel(parent)
-		ch := make(chan struct{})
-		p := synchronization.NewPeriodicalTrigger(ctx, "a periodical trigger", time.Millisecond*2, harness.Logger, func() {}, func() { close(ch) })
+		ticker := synchronization.NewHookTicker()
+		wasStopped := NewTestFlag(t)
+		ticker.Stop_ = func() { wasStopped.Toggle() }
```
Comment (electricmonk) [inline synchronization/trigger_test.go]: it seems like you use `Stop_` *or* `C_` but never both. If so, I'd either create separate make functions `NewHookTriggerWithChannel()` and `NewHookTriggerWithStopFunc(f)` and use either when appropriate.

File: synchronization/trigger_test.go [hunk 7]
```diff
@@ -26,120 +26,133 @@ func newNopLogger() *nopLogger {
...
+		defer p.Stop()
 		harness.Supervise(p)
-		time.Sleep(time.Microsecond * 1100)
-		p.Stop()
-		xValueOnStop := x
-		time.Sleep(time.Millisecond * 5)
-		require.Equal(t, xValueOnStop, x, "expected one tick due to stop")
-
+		for i := 0; i < 5; i++ {
+			ch <- time.Now()
```
Comment (vistra) [inline synchronization/trigger_test.go]: following @electricmonk's comment above, can this be wrapped in a `HookTicker` method (`ticker.tick()`)?

File: synchronization/trigger_test.go [hunk 8]
```diff
@@ -26,120 +26,133 @@ func newNopLogger() *nopLogger {
...
+// simple, thread-safe testing tool
+type TestFlag struct {
+	t     testing.TB
+	count uint32
+}
+
+func NewTestFlag(t testing.TB) *TestFlag {
+	return &TestFlag{
+		t:     t,
+		count: 0,
```
Comment (vistra) [inline synchronization/trigger_test.go]: it's not really a count right?

File: synchronization/trigger.go [hunk 9]
```diff
@@ -13,41 +13,82 @@ import (
...
+	return t.C_()
+}
+
+func (t *HookTicker) Stop() {
+	t.Stop_()
+}
+
+var noopChannel = make(chan time.Time)
+
+func NewHookTicker() *HookTicker {
```
Comment (vistra) [inline synchronization/trigger.go]: This was mentioned in other comments but i'll summarise here - maybe consider simplifying the usage of `HookTicker` by:
1. Having `HookTicker` manage the trigger channel internally (not exposed)
2. Add a `tick()` (writes to the channel)
3. Add an `isStopped` property (set by `.Stop()`), and an `IsStopped()` getter. 
I think it would make `HookTicker` just as powerful, but would make the usage much simpler and clearer.

File: synchronization/trigger_test.go (hunk 3 above)
Comment (amir-arad) [reply synchronization/trigger_test.go]: no reason. code heritage.

File: synchronization/trigger_test.go (hunk 5 above)
Comment (amir-arad) [reply synchronization/trigger_test.go]: that would be more expressive but I don't think increasing readability for these tests justify the boilerplate. I went with a single `TestTicker`  implementation instead. WDYT?

File: synchronization/trigger_test.go (hunk 8 above)
Comment (amir-arad) [reply synchronization/trigger_test.go]: right

File: synchronization/trigger.go (hunk 9 above)
Comment (amir-arad) [reply synchronization/trigger.go]: see the new `TestTicker`
