### PR TITLE
Sync batch exceeds outgoing connection capacity 

### LINKED ISSUE #1514: BlockSync - a node too far behind may stop syncing forever
A block sync request asks for a range of blocks, of a size defined in the node configuration.  If the chunk size (in bytes) is larger than the transport queue size (currently 20mb), the transmission of the chunk is guaranteed to fail. 

The chunk size configuration is defined by number of blocks per chunk, not by number of bytes. So the chunk size in bytes may vary significantly depending of the size of the blocks in the range. 

If the configuration allows, a node too far behind may ask for a chunk too-large to fit the send queue buffer, and the sync will never advance.

root cause of #1511

### PR DESCRIPTION
**Pull request by ronnno**
resolves #1514

### CODE REVIEW

File: services/gossip/adapter/tcp/outgoing_connections.go [hunk 1]
```diff
@@ -121,11 +121,17 @@ func (c *outgoingConnections) disconnectAll(ctx context.Context, peersToDisconne
...
 }
 
+var DataExceedsCapacityError = errors.Errorf("Data exceeds allowed size %d", SEND_QUEUE_MAX_BYTES)
+
 // TODO(https://github.com/orbs-network/orbs-network-go/issues/182): we are not currently respecting any intents given in ctx (added in context refactor)
 func (c *outgoingConnections) send(ctx context.Context, data *adapter.TransportData) error {
 	c.RLock()
 	defer c.RUnlock()
 
+	if data.TotalSize() > SEND_QUEUE_MAX_BYTES {
```
Comment (vistra) [inline services/gossip/adapter/tcp/outgoing_connections.go:131]: There is a small unhandled edge case here - the send queue can be partially full, causing this condition to pass but the subsequent transmission to fail silently as before

Comment (ronnno) [reply services/gossip/adapter/tcp/outgoing_connections.go:131]: Not really - if we wanted to address the case where the queue is temporarily full the correct behavior would be to wait for to to clear with a timeout.  
Consider that in the time that passes between the first failure and the second attempt with half the batch size the queue can be emptied. So halving the batch size is simply not the correct fix for this edge case. We will risk starvation in this case - unlikely as it may be
