### PR TITLE
ISSUE 1381: Prometheus metrics were not exported correctly

### LINKED ISSUE #1381: Prometheus histogram metrics are incorrect
**Describe the bug**

Prometheus histogram metrics have 2 bugs:

1) All `min` value (p=0) instead of actual percentile
2) Percentiles are incorrect - minimum should be `quantile=0` and not `quantile=0.01`, max should be `quantile=1` and the values in between do not correspond to the quantiles of the regular metrics.

See 
http://validator.orbs.com/vchains/1100000/metrics.prometheus
vs
http://validator.orbs.com/vchains/1100000/metrics

Look for `TransactionPool_ServiceTime_Millis` as a representative of any other histogram metric.
While /metrics report the various quantiles correctly, /metrics.prometheus prints the value of `min` quantile for all quantiles.

For example, the minimum quantile (p=0) is 838.8608.
Prometheus should report it on `quantile=0`.

```
PublicApi.SendTransactionProcessingTime.Millis: {
Name: "PublicApi.SendTransactionProcessingTime.Millis",
Min: 838.8608,
P50: 4831.838207,
P95: 7516.192767,
P99: 8589.934591,
Max: 9000,
Avg: 4445.96224,
Samples: 20
},
```
- vs -
```
# TYPE TransactionPool_ServiceTime_Millis histogram
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="0.01"} 838.8608
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="0.5"} 838.8608
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="0.95"} 838.8608
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="0.99"} 838.8608
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="0.999"} 838.8608
```

Correct prometheus values should be:
```
# TYPE TransactionPool_ServiceTime_Millis histogram
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="0"} 838.8608
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="0.5"} 4831.838207
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="0.95"} 7516.192767
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="0.99"} 8589.934591
PublicApi_SendTransactionProcessingTime_Millis{vcid="1100000",node="d5f2f401742568bcb6fc0fd54c2b2eb1b75f8556",quantile="1"} 9000

```

**Steps To Reproduce**
Always happens when accessing metrics in production or testnet.
See links to Orbs Audit node above.

### PR DESCRIPTION
**Pull request by IdoZilberberg**
Fixes #1381

### CODE REVIEW

File: instrumentation/metric/histogram_prometheus_test.go [hunk 1]
```diff
@@ -8,36 +8,59 @@
...
+	require.Regexp(t, "# TYPE Some_Latency histogram", promStr)
+	for _, row := range metrics["Some.Latency"].PrometheusRow() {
+		expectedStr := fmt.Sprintf("Some_Latency{vcid=\"100000\",quantile=\"%s\"} %s",
+			QuantileAsStr(row.quantile), row.value)
+		require.Regexp(t, expectedStr, promStr)
+	}
 
-	resultWithParams := r.ExportPrometheus()
-	require.Regexp(t, "Some_Latency{vcid=\"100000\",quantile=\"0.01\"} 0.00", resultWithParams)
+	//status := r.NewHistogram("Some.Latency", 10000)
```
Comment (netoneko) [inline instrumentation/metric/histogram_prometheus_test.go]: Please remove commented out code

File: instrumentation/metric/prometheus.go [hunk 2]
```diff
@@ -26,25 +26,29 @@ func prometheusName(name string) string {
...
+	if len(labels) > 0 {
+		return `{` + strings.Join(labels, ",") + `}`
 	}
 
 	return ""
 }
 
-func (r *prometheusRow) String(pairs ...prometheusKeyValuePair) string {
-	return r.name + r.wrapParams(pairs...) + " " + r.value
+func QuantileAsStr(quantile float64) string {
```
Comment (electricmonk) [inline instrumentation/metric/prometheus.go]: why is this exported?

File: instrumentation/metric/histogram_prometheus_test.go [hunk 3]
```diff
@@ -8,36 +8,59 @@
...
+		histo.Record(int64(i) * SEC)
+	}
+
+	metrics := r.ExportAll()
+	prometheusStrings := MetricsToPrometheusStrings(metrics, nil)
+	promStr := r.ExportPrometheus()
+	fmt.Println(prometheusStrings)
+	require.Regexp(t, "# TYPE Some_Latency histogram", promStr)
+	for _, row := range metrics["Some.Latency"].PrometheusRow() {
+		expectedStr := fmt.Sprintf("Some_Latency{quantile=\"%s\"} %s",
```
[the remark this answers is not in the document]
Comment (IdoZilberberg) [reply instrumentation/metric/histogram_prometheus_test.go]: I like this better as regexp, it is more resilient. If I were to compare an exact string match, it might break on newlines, spaces and such.

File: instrumentation/metric/prometheus.go (hunk 2 above)
Comment (IdoZilberberg) [reply instrumentation/metric/prometheus.go]: Fixed

File: instrumentation/metric/histogram_prometheus_test.go (hunk 1 above)
Comment (IdoZilberberg) [reply instrumentation/metric/histogram_prometheus_test.go]: Removed.

**Comment by IdoZilberberg** [comment]
@electricmonk @netoneko There were 2 histogram tests - one that has no `vcid` label and another that does. I felt this is redundant so I kept only the one that has `vcid`.
LMK if you think otherwise. I'll wait before merging it.

File: instrumentation/metric/prometheus.go [hunk 4]
```diff
@@ -26,25 +26,30 @@ func prometheusName(name string) string {
...
+	if len(labels) > 0 {
+		return `{` + strings.Join(labels, ",") + `}`
 	}
 
 	return ""
 }
 
-func (r *prometheusRow) String(pairs ...prometheusKeyValuePair) string {
-	return r.name + r.wrapParams(pairs...) + " " + r.value
+func quantileAsStr(quantile float64) string {
```
Comment (golangcibot) [inline instrumentation/metric/prometheus.go]: `quantileAsStr` is unused (from `deadcode`)

**Comment by IdoZilberberg** [comment]
@netoneko I renamed `quantile` to `aggregation` and added missing aggregations.
See: https://github.com/orbs-network/orbs-network-go/issues/1381#issuecomment-545402749

^ @electricmonk
