### PR TITLE
e2e shared state

### LINKED ISSUE #482: Update e2e to always use random accounts
Right now the `e2e_testnet` step on CI is broken because we rely on the fact that e2e always starts with a clean system: https://circleci.com/gh/orbs-network/orbs-network-go/3633

Now that I have added a step that verifies that the leader was actually synced before proceeding with deployment of other nodes, e2e understandably fails.

### PR DESCRIPTION
**Pull request by electricmonk**
fixes #482

### CODE REVIEW

File: test/e2e/main_test.go [hunk 1]
```diff
@@ -8,7 +8,12 @@ import (
 func TestMain(m *testing.M) {
 	cleanNativeProcessorCache()
 
-	exitCode := m.Run()
+	n := newInProcessE2ENetwork()
+
+	m.Run()
+	exitCode := m.Run() // run twice so that any test assuming a clean slate will fail; e2es shouldn't assume anything about system state
```
Comment (talkol) [inline test/e2e/main_test.go]: It's cool we run twice, although it's the slowest test and now we run it twice.. are we sure we always want to do this?

File: services/processor/native/repository/BenchmarkToken/contract.go [hunk 2]
```diff
@@ -24,7 +24,7 @@ type contract struct{ *sdk.BaseContract }
 
 ///////////////////////////////////////////////////////////////////////////
 
-const TOTAL_SUPPLY = 10000
+const TOTAL_SUPPLY = 1000000
```
Comment (talkol) [inline services/processor/native/repository/BenchmarkToken/contract.go]: This doesn't really solve the problem for the forever live test net
Eventually it will run out of tokens
It runs twice successfully but won't survive infinite runs

Comment (talkol) [reply services/processor/native/repository/BenchmarkToken/contract.go]: Opened an issue https://github.com/orbs-network/orbs-network-go/issues/500
