### PR TITLE
Serve HTTP requests early

### LINKED ISSUE #1371: HTTP server does not respond until the state is processed
Seems like http calls are blocked until the state is synced with block storage, which takes several minutes.

This impedes our monitoring efforts.

How to reproduce: generate a huge block file with a bunch of transactions and try to connect to the public api via http.

### PR DESCRIPTION
**Pull request by vistra**
fixes #1371 

This will make the HTTP server launch immediately and serve non public-api endpoints (metrics, robots.txt, etc) while the node is initializing.

### CODE REVIEW

File: bootstrap/httpserver/server_handlers_test.go [hunk 1]
```diff
@@ -222,6 +223,51 @@ func TestHttpServer_Robots(t *testing.T) {
 	})
 }
 
+func TestPublicApiResponds503UntilPublicApiIsRegistered(t *testing.T) {
+	with.Logging(t, func(harness *with.LoggingHarness) {
+		h := newHarnessWithUnregisteredPublicApi(harness)
+		defer h.server.Shutdown()
+		port := h.server.Port()
```
Comment (electricmonk) [inline bootstrap/httpserver/server_handlers_test.go]: since you already have a harness, you could push the http request logic, including crafting the url, into the harness

File: bootstrap/httpserver/server_handlers_test.go [hunk 2]
```diff
@@ -222,6 +223,51 @@ func TestHttpServer_Robots(t *testing.T) {
...
+
+		request := (&client.GetBlockRequestBuilder{BlockHeight: 1}).Build()
+		req, _ := http.NewRequest("POST", fmt.Sprintf("http://127.0.0.1:%d/api/v1/get-block", port), bytes.NewReader(request.Raw()))
+
+		//defer h.server.GracefulShutdown()
```
Comment (electricmonk) [inline bootstrap/httpserver/server_handlers_test.go]: please don't leave commented-out code in our codebase

**Comment by vistra** [comment]
@electricmonk addressed your comments but also made a bit of refactoring, please review

File: bootstrap/httpserver/server_handlers_test.go [hunk 3]
```diff
@@ -27,244 +27,244 @@ import (
 
 func TestHttpServer_SendTransaction_Basic(t *testing.T) {
 	with.Logging(t, func(parent *with.LoggingHarness) {
-		h := newHarness(parent)
+		withServerHarness(parent, func(h *harness) {
```
Comment (electricmonk) [inline bootstrap/httpserver/server_handlers_test.go]: out of curiosity, why did you change the pattern to accept a func taking the harness?

Comment (vistra) [reply bootstrap/httpserver/server_handlers_test.go]: because the harness now needs to be shut down, and that way the wrapper handles it instead of the tests

**Comment by netoneko** [comment]
Are you guys going to merge that?
