### PR TITLE
resolve #1232

### LINKED ISSUE #1232: Flakiness in direct transport: concurrent map read and map write
**Describe the bug**

**Steps To Reproduce**
flaky

**Logs**

```
info 2019-07-16T11:36:35.258994Z copying blocks file source=/Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/test/e2e/_data/blocks target=/tmp/orbs/e2e/a328846cd5b4979d68a8c58a9bdfeee657b34de7/blocks function=e2e.deployBlockStorageFiles source=test/e2e/file_utils.go:68 _test=e2e _branch= _commit= 
info 2019-07-16T11:36:35.280098Z built index node=a328846cd5b4979d68a8c58a9bdfeee657b34de7 adapter=block-storage valid-block-bytes=349720 block-height=538 function=filesystem.buildIndex source=services/blockstorage/adapter/filesystem/file_system_persistence.go:212 _test=e2e _branch= _commit= 
fatal error: concurrent map read and map write
info 2019-07-16T11:36:35.280353Z attempting outgoing transport connection node=a328846cd5b4979d68a8c58a9bdfeee657b34de7 adapter=gossip peer=127.0.0.1:46164 entry-point=Gossip.Transport.TCP.Client.127.0.0.1:46164 request-id=Gossip.Transport.TCP.Client.127.0.0.1:46164-1563276995280327000 function=tcp.(*DirectTransport).clientMainLoop source=services/gossip/adapter/tcp/direct_outgoing.go:24 _test=e2e _branch= _commit= 
goroutine 36 [running]:
runtime.throw(0x490e9b5, 0x21)
    /usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:617 +0x72 fp=0xc00018d698 sp=0xc00018d668 pc=0x402f712
runtime.mapaccess1_faststr(0x47e6560, 0xc00038b380, 0xc0001fd760, 0x14, 0xc0000c65f0)
    /usr/local/Cellar/go/1.12.6/libexec/src/runtime/map_faststr.go:21 +0x469 fp=0xc00018d708 sp=0xc00018d698 pc=0x40148e9
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).connect.func1()
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:111 +0x67 fp=0xc00018d758 sp=0xc00018d708 pc=0x466ab07
github.com/orbs-network/orbs-network-go/synchronization/supervised.tryOnce(0x82bf050, 0xc0000b8300, 0xc00038b3e0)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:60 +0x57 fp=0xc00018d788 sp=0xc00018d758 pc=0x44830b7
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc000184120, 0x82bf050, 0xc0000b8300, 0xc00038b3e0, 0x4a76fc0, 0xc00019c340)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:41 +0x69 fp=0xc00018d7b0 sp=0xc00018d788 pc=0x4483a49
runtime.goexit()
    /usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00018d7b8 sp=0xc00018d7b0 pc=0x405fac1
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e
goroutine 1 [runnable]:
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).connect(0xc0003a1f80, 0x4a76fc0, 0xc00019c340, 0xc0001fd880, 0x14, 0x4a68100, 0xc0001a1b80)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:105 +0x165
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.NewDirectTransport(0x4a76fc0, 0xc00019c340, 0x82bf008, 0xc0001be8c0, 0x4a7fb20, 0xc00009c900, 0x4a800a0, 0xc00019c380, 0x4a7dac0)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:93 +0x30e
github.com/orbs-network/orbs-network-go/bootstrap.NewNode(0x8845600, 0xc0001be8c0, 0x4a7fb20, 0xc00009c660, 0x14, 0x14)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/bootstrap/node.go:53 +0x410
github.com/orbs-network/orbs-network-go/test/e2e.bootstrapE2ENetwork(0x48fd8d6, 0xd, 0x0)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/test/e2e/network.go:100 +0xfcd
github.com/orbs-network/orbs-network-go/test/e2e.NewInProcessE2ENetwork(0x1000000002a)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/test/e2e/network.go:35 +0x46
github.com/orbs-network/orbs-network-go/test/e2e.TestMain(0xc0001a2280)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/test/e2e/main_test.go:24 +0x77
main.main()
    _testmain.go:48 +0x13e
goroutine 20 [chan receive]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc0001aa0f0)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_recursive.go:125 +0xc7
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newRecursiveTree
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_recursive.go:119 +0x133
goroutine 21 [syscall, locked to thread]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
    _cgo_gotypes.go:224 +0x41
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.init.1.func1()
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:72 +0x3c
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.init.1
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:63 +0x4e
goroutine 22 [chan receive]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x50e2140)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/metrics/meter.go:289 +0x78
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/metrics.NewMeterForced
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/metrics/meter.go:70 +0xfa
goroutine 23 [select]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).remote(0xc0001e0000, 0x0, 0x0, 0x0, 0x0)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:307 +0x51c
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/consensus/ethash.New
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:496 +0x35c
goroutine 24 [chan receive]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000196c10)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f
goroutine 25 [chan receive]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000196c10)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f
goroutine 26 [chan receive]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000196c10)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f
goroutine 27 [chan receive]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000196c10)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x97
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.newTxSenderCacher
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f
goroutine 28 [syscall]:
os/signal.signal_recv(0x0)
    /usr/local/Cellar/go/1.12.6/libexec/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
    /usr/local/Cellar/go/1.12.6/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
    /usr/local/Cellar/go/1.12.6/libexec/src/os/signal/signal_unix.go:29 +0x41
goroutine 29 [chan receive]:
github.com/orbs-network/orbs-network-go/services/blockstorage/adapter/filesystem.closeOnContextDone.func1(0x4a76fc0, 0xc00019c340, 0xc0001980f8, 0x4a7fb20, 0xc00009c960)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/adapter/filesystem/file_system_persistence.go:177 +0x4c
created by github.com/orbs-network/orbs-network-go/services/blockstorage/adapter/filesystem.closeOnContextDone
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/adapter/filesystem/file_system_persistence.go:176 +0x67
goroutine 35 [runnable]:
fmt.(*fmt).fmtInteger(0xc0003b0040, 0xb452, 0xa, 0x0, 0x49004b6, 0x11)
    /usr/local/Cellar/go/1.12.6/libexec/src/fmt/format.go:194 +0x4af
fmt.(*pp).fmtInteger(0xc0003b0000, 0xb452, 0x6400000000)
    /usr/local/Cellar/go/1.12.6/libexec/src/fmt/print.go:380 +0x1e5
fmt.(*pp).printArg(0xc0003b0000, 0x47b7740, 0xc00038d68c, 0x64)
    /usr/local/Cellar/go/1.12.6/libexec/src/fmt/print.go:676 +0x954
fmt.(*pp).doPrintf(0xc0003b0000, 0x48f6767, 0x3, 0xc00006ee08, 0x1, 0x1)
    /usr/local/Cellar/go/1.12.6/libexec/src/fmt/print.go:1016 +0x158
fmt.Sprintf(0x48f6767, 0x3, 0xc00018ce08, 0x1, 0x1, 0x0, 0x0)
    /usr/local/Cellar/go/1.12.6/libexec/src/fmt/print.go:214 +0x66
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).serverListenForIncomingConnections(0xc0003a1f80, 0x4a76fc0, 0xc00019c340, 0xb452, 0x0, 0x0, 0x0, 0x0)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_incoming.go:24 +0xb2
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).serverMainLoop(0xc0003a1f80, 0x4a76fc0, 0xc00019c340, 0xc00038b452)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_incoming.go:53 +0x67
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.NewDirectTransport.func1()
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:87 +0x75
github.com/orbs-network/orbs-network-go/synchronization/supervised.tryOnce(0x82bf050, 0xc0000b8300, 0xc0001512a0)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:60 +0x57
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc0001840c0, 0x82bf050, 0xc0000b8300, 0xc0001512a0, 0x4a76fc0, 0xc00019c340)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:41 +0x69
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e
goroutine 37 [runnable]:
syscall.syscall(0x40abe60, 0x1, 0xc000250000, 0x1a9, 0x1a9, 0x0, 0x0)
    /usr/local/Cellar/go/1.12.6/libexec/src/runtime/sys_darwin.go:63 +0x2e
syscall.write(0x1, 0xc000250000, 0x1a9, 0x280, 0x0, 0xc000068c78, 0xc0003de000)
    /usr/local/Cellar/go/1.12.6/libexec/src/syscall/zsyscall_darwin_amd64.go:1621 +0x67
syscall.Write(...)
    /usr/local/Cellar/go/1.12.6/libexec/src/syscall/syscall_unix.go:191
internal/poll.(*FD).Write(0xc0000b8000, 0xc000250000, 0x1a9, 0x280, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.12.6/libexec/src/internal/poll/fd_unix.go:268 +0x179
os.(*File).write(...)
    /usr/local/Cellar/go/1.12.6/libexec/src/os/file_unix.go:280
os.(*File).Write(0xc0000b6000, 0xc000250000, 0x1a9, 0x280, 0x10b5d8e8, 0xc000068c90, 0x400bc9b)
    /usr/local/Cellar/go/1.12.6/libexec/src/os/file.go:145 +0x76
fmt.Fprintln(0x4a5fe60, 0xc0000b6000, 0xc000068d08, 0x1, 0x1, 0x4, 0x49155a1, 0x28)
    /usr/local/Cellar/go/1.12.6/libexec/src/fmt/print.go:266 +0x8b
github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/scribe/log.(*basicOutput).Append(0xc0001a1ba0, 0x48f6f88, 0x4, 0x49155a1, 0x28, 0xc0001a2380, 0xa, 0x10)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/scribe/log/basic_output.go:22 +0x12a
github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/scribe/log.(*basicLogger).Log(0xc0000b8300, 0x48f6f88, 0x4, 0x49155a1, 0x28, 0xc000197170, 0x2, 0x2)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/scribe/log/logger.go:130 +0x43f
github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/scribe/log.(*basicLogger).Info(0xc0000b8300, 0x49155a1, 0x28, 0xc000197170, 0x2, 0x2)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/scribe/log/logger.go:135 +0x72
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).clientMainLoop(0xc0003a1f80, 0x4a76fc0, 0xc00019c340, 0xc000154370)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_outgoing.go:24 +0x210
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).connect.func1()
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:111 +0x96
github.com/orbs-network/orbs-network-go/synchronization/supervised.tryOnce(0x82bf050, 0xc0000b8300, 0xc00038b410)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:60 +0x57
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc000184180, 0x82bf050, 0xc0000b8300, 0xc00038b410, 0x4a76fc0, 0xc00019c340)
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:41 +0x69
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
    /Users/ido/dev/orbs/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e
FAIL    github.com/orbs-network/orbs-network-go/test/e2e    0.069s
```

### PR DESCRIPTION
**Pull request by ronnno**
## Description

Concurrency issue fixed by adding read locks around access to state members in `DirectTransport`

### CODE REVIEW

File: services/gossip/adapter/tcp/direct_transport.go [hunk 1]
```diff
@@ -155,6 +158,12 @@ func (t *DirectTransport) Port() int {
 	return t.serverPort
 }
 
+func (t *DirectTransport) safeLenOfOutgoingPeerQueues() int {
```
Comment (golangcibot) [inline services/gossip/adapter/tcp/direct_transport.go]: U1000: func `(*DirectTransport).safeLenOfOutgoingPeerQueues` is unused (from `unused`)
