### PR TITLE
Issue/1291

### LINKED ISSUE #1291: TestService_SlowBlockCreationDoesNotHurtBlockSync
**Describe the bug**

The test fails rarely in CI during testing phase in a way which appears to be related to timing issues: `EventuallyVerify()` does not complete in 40 millis. Stalling/Jitter may be the cause for flakiness in CI.
However, there is more to it. The same error happens consistently in dev env when running the test with `-count 2` starting from the merge of #1255 

**Steps To Reproduce**

Checkout master revision after the merge of #1255. Run the test `TestService_SlowBlockCreationDoesNotHurtBlockSync` with repetition of `-count 2` 

Alternately, a single run breaks flakily in CI

**Logs**

https://circleci.com/gh/orbs-network/orbs-network-go/18104?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

### PR DESCRIPTION
**Pull request by ronnno**
resolves #1291 
Reinterpret the test scenario and simplify. 
renaming test to: `TestService_DoesNotProposeNewBlocksWhileSyncingBlocksSequentially`

and implementing without shared memory

### CODE REVIEW

File: services/consensusalgo/leanhelixconsensus/test/harness.go [hunk 1]
```diff
@@ -37,20 +37,36 @@ type harness struct {
...
+	h := &harness{
+		gossip:                 &gossiptopics.MockLeanHelix{},
+		blockStorage:           &services.MockBlockStorage{},
+		consensusContext:       &services.MockConsensusContext{},
+		auditBlocksYoungerThan: auditBlocksYoungerThan,
+	}
 
-	blockStorage := &services.MockBlockStorage{}
-	blockStorage.When("RegisterConsensusBlocksHandler", mock.Any).Return().Times(1)
+	h.resetMocks()
```
Comment (electricmonk) [inline services/consensusalgo/leanhelixconsensus/test/harness.go]: why reset mocks at the start up the test?

Comment (electricmonk) [reply services/consensusalgo/leanhelixconsensus/test/harness.go]: ok, the term reset is not really good here

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go [hunk 2]
```diff
@@ -24,44 +21,39 @@ import (
...
-		isLeanHelixStuckOnCreatingABlock := false
+		h.expectConsensusContextRequestNewBlockNotCalled()
 
-		h.expectConsensusContextRequestOrderingCommittee(0) // we're index 0 (first time called)
-		h.expectConsensusContextRequestOrderingCommittee(0) // we're index 0 (second time called)
-		// TODO REMOVE LINE h.expectGossipSendLeanHelixMessage()
-		h.consensusContextRespondWithVerySlowBlockCreation(&isLeanHelixStuckOnCreatingABlock)
+		h.expectConsensusContextRequestOrderingCommittee(0, 1) // we're index 0 (first time called)
+		mockFuncRequestOrderingCommittee := h.consensusContext.Functions[len(h.consensusContext.Functions)-1]
+		require.Equal(t, "RequestOrderingCommittee", mockFuncRequestOrderingCommittee.Name, "expected last registered mock function to be mockFuncRequestOrderingCommittee.Name")
```
Comment (electricmonk) [inline services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: why?

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go [hunk 3]
```diff
@@ -24,44 +21,39 @@ import (
...
 
-		isLeanHelixStuckOnCreatingABlock := false
+		h.expectConsensusContextRequestNewBlockNotCalled()
 
-		h.expectConsensusContextRequestOrderingCommittee(0) // we're index 0 (first time called)
-		h.expectConsensusContextRequestOrderingCommittee(0) // we're index 0 (second time called)
-		// TODO REMOVE LINE h.expectGossipSendLeanHelixMessage()
-		h.consensusContextRespondWithVerySlowBlockCreation(&isLeanHelixStuckOnCreatingABlock)
+		h.expectConsensusContextRequestOrderingCommittee(0, 1) // we're index 0 (first time called)
+		mockFuncRequestOrderingCommittee := h.consensusContext.Functions[len(h.consensusContext.Functions)-1]
```
Comment (electricmonk) [inline services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: this is fragile if I understand what you did here

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go [hunk 4]
```diff
@@ -24,44 +21,39 @@ import (
...
 		h := newLeanHelixServiceHarness(0).start(t, ctx)
 
-		isLeanHelixStuckOnCreatingABlock := false
+		h.expectConsensusContextRequestNewBlockNotCalled()
 
-		h.expectConsensusContextRequestOrderingCommittee(0) // we're index 0 (first time called)
-		h.expectConsensusContextRequestOrderingCommittee(0) // we're index 0 (second time called)
-		// TODO REMOVE LINE h.expectGossipSendLeanHelixMessage()
-		h.consensusContextRespondWithVerySlowBlockCreation(&isLeanHelixStuckOnCreatingABlock)
+		h.expectConsensusContextRequestOrderingCommittee(0, 1) // we're index 0 (first time called)
```
Comment (electricmonk) [inline services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: you're using `RequestOrderingCommittee` as a way to spy on the current view, right? if so, maybe wrap the function with a semantic function `expectCurrentViewToBe`

File: services/consensusalgo/leanhelixconsensus/test/harness.go [hunk 5]
```diff
@@ -84,10 +100,15 @@ func (h *harness) expectConsensusContextRequestOrderingCommitteeNotCalled() {
 	h.consensusContext.When("RequestOrderingCommittee", mock.Any, mock.Any).Return(nil, nil).Times(0)
 }
 
-func (h *harness) expectConsensusContextRequestOrderingCommittee(leaderNodeIndex int) {
+func (h *harness) expectConsensusContextRequestOrderingCommittee(leaderNodeIndex int, times int) {
```
Comment (electricmonk) [inline services/consensusalgo/leanhelixconsensus/test/harness.go]: `times` is never more than 1, why do you expose it?

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go [hunk 6]
```diff
@@ -24,44 +21,39 @@ import (
...
 			Mode:                   handlers.HANDLE_BLOCK_CONSENSUS_MODE_UPDATE_ONLY,
 			BlockType:              protocol.BLOCK_TYPE_BLOCK_PAIR,
 			BlockPair:              b5,
 			PrevCommittedBlockPair: nil,
 		})
 
+		require.NoError(t, test.EventuallyVerify(test.EVENTUALLY_ACCEPTANCE_TIMEOUT, h.consensusContext), "expected ordering committee to be requested once")
+		require.NoError(t, test.ConsistentlyVerify(test.CONSISTENTLY_ACCEPTANCE_TIMEOUT, h.consensusContext), "expected new block not to be requested by lean helix")
+
+		h.ResetConsensusContextMock()
```
Comment (electricmonk) [inline services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: this is hiding the expectation not to request a block? why not use a `Never` clause?

File: services/consensusalgo/leanhelixconsensus/test/harness.go (hunk 1 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/harness.go]: Reset in the mock object means "clear all setup". but in the harness it means - switch back to harness defaults. so how about "ResetToDefault" ?...

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go (hunk 2 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: this is a relic from a past version... before i had "reset" functions - i'm removing it now...

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go (hunk 3 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: why?

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go (hunk 4 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: No, I'm using it to enforce leadership of node "0"

File: services/consensusalgo/leanhelixconsensus/test/harness.go (hunk 5 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/harness.go]: reverting... another relic of a previous version

File: services/consensusalgo/leanhelixconsensus/test/harness.go (hunk 1 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/harness.go]: `resetAndApplyMockDefaults`?

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go (hunk 6 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: `Never` is wrapped by a harness function in line 28

File: services/consensusalgo/leanhelixconsensus/test/harness.go (hunk 1 above)
Comment (electricmonk) [reply services/consensusalgo/leanhelixconsensus/test/harness.go]: ja

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go (hunk 3 above)
Comment (electricmonk) [reply services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: because if it's no longer the last function?

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go (hunk 4 above)
Comment (electricmonk) [reply services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: then rename something like `onRequestOrderingComitteeReturnNodeIndexAsLeader`

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go (hunk 3 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: its gone already... this was garbage code i forgot to clean up.

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go (hunk 4 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: this works?
`h.beFirstInCommittee() // we will be leader after sync:`

File: services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go (hunk 6 above)
Comment (ronnno) [reply services/consensusalgo/leanhelixconsensus/test/leader_elected_by_sync_does_not_immediately_propose_block_test.go]: renamed to `h.expectNeverToProposeABlock()`

**Comment by ronnno** [comment]
converted to a loop and renamed test
